jenkins:
  numExecutors: 10
jobs:
  - script: >
      multibranchPipelineJob('validation-job') {
          branchSources {
              git {
                  remote("https://github.com/piper-validation/cloud-s4-sdk-book")
                  includes('validate-cx-server')
              }
          }
      }
