steps:
  githubPublishRelease:
    addClosedIssues: true
    addDeltaToLastRelease: true
    excludeLabels:
      - 'discussion'
      - 'duplicate'
      - 'invalid'
      - 'question'
      - 'wontfix'
    owner: 'SAP'
    repository: 'devops-docker-cx-server'
    releaseBodyHeader: ''
