@Library('piper-library-os') _

import com.sap.piper.ConfigurationHelper
import groovy.transform.Field

@Field String STEP_NAME = 'testing'

node("master") {
    stage('Reproduce issue') {
        Map configuration = ConfigurationHelper.newInstance(this)
            .use()
    }
}
