name: Release new Release (tagged version)

on:
  release:
    types: [published]

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build and smoke-test a release candidate of the Docker image
      run: ./ci.sh ${GITHUB_REF##*/} ${{ secrets.DOCKERHUB_PASSWORD }} ${{ secrets.DOCKERHUB_USER }}
