name: Build images and push master commits or on schedule

on:
  push:
    branches:
      - "**"
  schedule:
    - cron:  '0 6 * * 1-4'

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build and smoke-test a release candidate of the Docker image
      run: ./ci.sh latest  ${{ secrets.DOCKERHUB_PASSWORD }} ${{ secrets.DOCKERHUB_USER }}
