name: Release new Release (manual release)

on:
  release:
    types: [published]

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build, test and push
      run: ./ci.sh ${GITHUB_REF##*/} ${{ secrets.DOCKERHUB_PASSWORD }} ${{ secrets.DOCKERHUB_USER }}
